import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { withFileLock } from './file-lock.js';
import { nameKey } from './model.js';
import { isCurrentlyJoined } from './runtime.js';
import type { HostLedgerPort, HostLedgerScope, PresenceRecord, PresenceKey, PresenceLookup, PresenceResult, PresenceClaimResult, EvidenceRecord, EvidenceClaim, EvidenceRelease, EvidenceLookup, EvidenceGc, ClaimResult, ReconcileBindingInput, ReconcileBindingResult, WakeDispatchClaim, WakeDispatchClaimInput, WakeDispatchReleaseInput, WakeDispatchTransitionInput, WakeAttemptLookup } from './host-ledger.js';
const LOCK = { retryMs: 10 } as const; const RETENTION = 7 * 86400000;
export interface HostLedgerFileAdapterOptions { userPath?: string; localPath?: string; writableScope?: HostLedgerScope; readableScopes?: readonly HostLedgerScope[]; claimsPath?: string; now?: () => number }
async function canon(value:string):Promise<string>{const absolute=path.resolve(value);try{return await fs.realpath(absolute)}catch{return absolute}}
async function read<T extends {v:1;at?:number;updatedAt?:number}>(file:string,now:number,includeFuture=false):Promise<T[]>{try{return (await fs.readFile(file,'utf8')).split('\n').flatMap(line=>{try{const row=JSON.parse(line) as T;const at=row.at??row.updatedAt;return row.v===1&&typeof at==='number'&&at>=now-RETENTION&&(includeFuture||at<=now)?[row]:[]}catch{return[]}})}catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT')return[];throw e}}
async function write<T>(file:string,rows:readonly T[]):Promise<void>{await fs.mkdir(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.${Date.now()}.tmp`;await fs.writeFile(tmp,rows.length?rows.map(row=>JSON.stringify(row)).join('\n')+'\n':'',{mode:0o600});await fs.rename(tmp,file)}
function k(v:{location:string;participant:string;session:string;channel?:string;activity?:string;kind?:string}){return JSON.stringify([v.location,nameKey(v.participant),v.session,v.channel,v.activity,v.kind])}
function evidenceKey(v:{location:string;participant:string;session:string;activity:string;kind:string;attemptN?:number}){return JSON.stringify([v.location,nameKey(v.participant),v.session,v.activity,v.kind,v.attemptN??null])}
interface ClaimRow { readonly v:1; readonly ts:number; readonly attention_key:string; readonly leaseId:string; readonly expiresAt:number; readonly phase:'claimed'|'dispatching'; readonly ownerPid?:number; readonly routeKind?:import('./model.js').WakeRouteKind; readonly attemptN?:number; readonly session?:string }
async function readClaims(file:string,now:number):Promise<ClaimRow[]>{try{return (await fs.readFile(file,'utf8')).split('\n').flatMap(line=>{try{const row=JSON.parse(line) as ClaimRow;return row.v===1&&typeof row.ts==='number'&&typeof row.attention_key==='string'&&typeof row.leaseId==='string'&&typeof row.expiresAt==='number'&&(row.phase==='claimed'||row.phase==='dispatching')&&row.ts>=now-RETENTION?[row]:[]}catch{return[]}})}catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT')return[];throw e}}
function processAlive(pid:number|undefined):boolean|undefined { if (pid===undefined) return undefined; try { process.kill(pid, 0); return true; } catch (error) { return (error as NodeJS.ErrnoException).code === 'ESRCH' ? false : true; } }
async function writeClaims(file:string,rows:readonly ClaimRow[]):Promise<void>{await fs.mkdir(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.${Date.now()}.tmp`;await fs.writeFile(tmp,rows.length?rows.map(row=>JSON.stringify(row)).join('\n')+'\n':'',{mode:0o600});await fs.rename(tmp,file)}
export class FileHostLedgerPort implements HostLedgerPort { private readonly user:string;private readonly local:string;private readonly writable:HostLedgerScope;private readonly readable:readonly HostLedgerScope[];private readonly claims:string;private readonly clock:()=>number; constructor(o:HostLedgerFileAdapterOptions={}){const testRoot=process.env.SQUARE_REGISTRY?path.dirname(process.env.SQUARE_REGISTRY):undefined;this.user=o.userPath??(testRoot??path.join(os.homedir(),'.square','host-ledger'));this.local=o.localPath??(testRoot??path.join(process.cwd(),'.square','host-ledger'));this.writable=o.writableScope??'local';this.readable=o.readableScopes??['user','local'];this.claims=o.claimsPath??path.join(this.user,'wake-claims.ndjsonl');this.clock=o.now??Date.now} private file(s:HostLedgerScope,f:'presence'|'evidence'){return path.join(s==='user'?this.user:this.local,`${f}.ndjsonl`)}
async claimPresence(i:PresenceRecord, scope:HostLedgerScope=this.writable):Promise<PresenceClaimResult>{const location=await canon(i.location),r={...i,location,...(scope==='local'?{route:undefined}:{}),updatedAt:i.updatedAt??this.clock(),v:1 as const},lock=path.join(this.user,'presence-claim.lock');try{return await withFileLock(lock,LOCK,async()=>{const candidates:any[]=[];for(const s of ['user','local'] as const){for(const row of await read<any>(this.file(s,'presence'),this.clock(),true)){if(row.location!==location||nameKey(row.participant)!==nameKey(r.participant))continue;candidates.push(s==='user'?row:{...row,route:undefined})}}const existing=candidates.sort((a,b)=>(b.updatedAt??0)-(a.updatedAt??0))[0];if(existing!==undefined){if(existing.session===r.session)return{status:'owned',record:existing};return{status:'busy',record:existing}}const f=this.file(scope,'presence');await withFileLock(f+'.lock',LOCK,async()=>write(f,[...(await read<typeof r>(f,this.clock(),true)).filter(x=>k(x)!==k(r)),r]));return{status:'acquired',record:r}})}catch(error){return{status:'degraded',record:r,error}}}
async ensurePresence(i:PresenceRecord, scope:HostLedgerScope=this.writable):Promise<PresenceResult>{const r={...i,location:await canon(i.location),...(scope==='local'?{route:undefined}:{}),updatedAt:i.updatedAt??this.clock(),v:1 as const};const f=this.file(scope,'presence');try{await withFileLock(f+'.lock',LOCK,async()=>write(f,[...(await read<typeof r>(f,this.clock(),true)).filter(x=>k(x)!==k(r)),r]));return{status:'ensured',record:r}}catch(error){return{status:'degraded',record:r,error}}}
async removePresence(i:PresenceKey){const r={...i,location:await canon(i.location)},f=this.file(this.writable,'presence');await withFileLock(f+'.lock',LOCK,async()=>write(f,(await read<any>(f,this.clock(),true)).filter(x=>k(x)!==k(r))))}
async listPresence(i:PresenceLookup={}):Promise<readonly PresenceRecord[]>{const loc=i.location===undefined?undefined:await canon(i.location),m=new Map<string,{record:any;scope:HostLedgerScope}>();for(const s of i.scopes??this.readable)for(const r of await read<any>(this.file(s,'presence'),i.now??this.clock())){if(loc&&r.location!==loc||i.participant&&nameKey(r.participant)!==nameKey(i.participant)||i.session&&r.session!==i.session)continue;const x=s==='user'?r:{...r,route:undefined},key=k(x),old=m.get(key);if(old?.scope==='user'&&s==='local')continue;if(!old||s==='user'||x.updatedAt>=old.record.updatedAt)m.set(key,{record:x,scope:s})}return[...m.values()].map(({record})=>record)}
async claimWakeDispatch(i:WakeDispatchClaimInput):Promise<WakeDispatchClaim>{const location=await canon(i.attention.squarePath),key=JSON.stringify([location,nameKey(i.attention.recipient),i.attention.actIndex,i.session??null,'wake']),at=i.at??this.clock();return withFileLock(`${this.claims}.lock`,LOCK,async()=>{const rows=await readClaims(this.claims,at),existing=rows.find((row)=>row.attention_key===key);if(existing?.phase==='dispatching'){const alive=processAlive(existing.ownerPid);if(existing.expiresAt<=at||alive===false)return{type:'ambiguous',lease:existing};return{type:'busy'}}if(existing!==undefined&&existing.expiresAt>at)return{type:'busy'};const next={v:1 as const,ts:at,attention_key:key,leaseId:i.leaseId,expiresAt:at+i.leaseMs,phase:'claimed' as const,ownerPid:process.pid,...(i.session===undefined?{}:{session:i.session})};await writeClaims(this.claims,[...rows.filter((row)=>row.attention_key!==key),next]);return{type:'acquired',leaseId:i.leaseId}})}
async transitionWakeDispatch(i:WakeDispatchTransitionInput):Promise<boolean>{const location=await canon(i.attention.squarePath),key=JSON.stringify([location,nameKey(i.attention.recipient),i.attention.actIndex,i.session??null,'wake']),at=i.at??this.clock();return withFileLock(`${this.claims}.lock`,LOCK,async()=>{const rows=await readClaims(this.claims,at),current=rows.find((row)=>{if(row.leaseId!==i.leaseId)return false;try{const parts=JSON.parse(row.attention_key) as unknown[];return parts[0]===location&&parts[1]===nameKey(i.attention.recipient)&&parts[2]===i.attention.actIndex}catch{return false}});if(current===undefined)return false;const next={v:1 as const,ts:at,attention_key:key,leaseId:i.leaseId,expiresAt:at+i.leaseMs,phase:i.phase,ownerPid:current.ownerPid,...(i.routeKind===undefined?{}:{routeKind:i.routeKind}),...(i.attemptN===undefined?{}:{attemptN:i.attemptN}),...(i.session===undefined?{}:{session:i.session})};await writeClaims(this.claims,[...rows.filter((row)=>row!==current),next]);return true})}
async releaseWakeDispatch(i:WakeDispatchReleaseInput):Promise<void>{const location=await canon(i.attention.squarePath),key=JSON.stringify([location,nameKey(i.attention.recipient),i.attention.actIndex,i.session??null,'wake']),at=i.at??this.clock();await withFileLock(`${this.claims}.lock`,LOCK,async()=>{const rows=await readClaims(this.claims,at);await writeClaims(this.claims,rows.filter((row)=>row.attention_key!==key||row.leaseId!==i.leaseId))})}
async listWakeAttempts(i:WakeAttemptLookup={}):Promise<readonly EvidenceRecord[]>{const attention=i.attention;return this.listEvidence({ kind:'wake', ...(attention===undefined?{}:{ location:await canon(attention.squarePath), participant:attention.recipient, activity:`act/${attention.actIndex}` }), ...(i.session===undefined?{}:{session:i.session}), now:i.now })}
async appendWakeAttempt(i:EvidenceRecord):Promise<void>{if(i.kind!=='wake')throw new Error('Wake attempt rows require wake evidence kind');return this.appendEvidence(i)}
async claimEvidence(i:EvidenceClaim):Promise<ClaimResult>{const f=this.file('user','evidence'),at=i.now??this.clock(),{leaseMs,...claim}=i,r={...claim,location:await canon(i.location),outcome:'dispatching',at,expiresAt:at+leaseMs,v:1 as const};try{return await withFileLock(f+'.lock',LOCK,async()=>{const all=await read<any>(f,at,true),matching=all.filter(x=>x.kind===r.kind&&x.location===r.location&&nameKey(x.participant)===nameKey(r.participant)&&x.activity===r.activity&&x.session===r.session),old=matching.findLast(x=>x.outcome==='dispatching');if(old!==undefined&&typeof old.expiresAt==='number'&&old.expiresAt>at)return{status:'busy',record:old} as ClaimResult;const delivered=(r.kind==='wake'&&matching.some(x=>x.outcome==='accepted'))||(r.kind==='presentation'&&matching.some(x=>x.outcome==='presented'));if(delivered)return{status:'delivered',record:matching.findLast(x=>x.outcome==='accepted'||x.outcome==='presented')} as ClaimResult;await write(f,[...all.filter(x=>!(x.kind===r.kind&&x.location===r.location&&nameKey(x.participant)===nameKey(r.participant)&&x.activity===r.activity&&x.session===r.session&&x.outcome==='dispatching')),r]);return{status:'acquired'} as ClaimResult})}catch(error){return{status:'degraded',error}}}
async releaseEvidence(i:EvidenceRelease):Promise<void>{const f=this.file('user','evidence'),location=await canon(i.location),at=i.now??this.clock();await withFileLock(f+'.lock',LOCK,async()=>write(f,(await read<any>(f,at,true)).filter(x=>!(x.kind===i.kind&&x.location===location&&nameKey(x.participant)===nameKey(i.participant)&&x.activity===i.activity&&x.session===i.session&&x.outcome==='dispatching'))))}
async appendEvidence(i:EvidenceRecord){const f=this.file('user','evidence'),r={...i,location:await canon(i.location),at:i.at??this.clock(),v:1 as const};await withFileLock(f+'.lock',LOCK,async()=>{const all=await read<any>(f,r.at,true);const base=all.filter(x=>k(x)===k(r));const replaceable=new Set(base.filter(x=>x.outcome==='dispatching'||(r.attemptN!==undefined&&x.attemptN===r.attemptN)).map(x=>evidenceKey(x)));await write(f,[...all.filter(x=>!(x.outcome==='dispatching'&&k(x)===k(r))&&!replaceable.has(evidenceKey(x))),r])})}
async listEvidence(i:EvidenceLookup={}):Promise<readonly EvidenceRecord[]>{const loc=i.location===undefined?undefined:await canon(i.location);return(await read<any>(this.file('user','evidence'),i.now??this.clock())).filter(r=>(!loc||r.location===loc)&&(!i.participant||nameKey(r.participant)===nameKey(i.participant))&&(!i.session||r.session===i.session)&&(!i.activity||r.activity===i.activity)&&(!i.kind||r.kind===i.kind))}
async gcEvidence(i:EvidenceGc){const f=this.file('user','evidence');await withFileLock(f+'.lock',LOCK,async()=>write(f,(await read<any>(f,this.clock())).filter(r=>r.at>=i.before)))}
async reconcileBinding(i:ReconcileBindingInput={}):Promise<ReconcileBindingResult>{let b:PresenceRecord[]=[];try{b=[...await this.listPresence({scopes:i.scopes,now:i.now})];if(i.artifact){const{state}=await i.artifact.read();const stale=b.filter(x=>!isCurrentlyJoined(state.acts as any,x.participant));for(const x of stale){for(const scope of i.scopes??this.readable){const remover=new FileHostLedgerPort({userPath:this.user,localPath:this.local,writableScope:scope,readableScopes:[scope],now:this.clock});await remover.removePresence(x)}}b=b.filter(x=>!stale.includes(x))}const latest=new Map<string,PresenceRecord>();for(const x of b){const key=JSON.stringify([x.location,nameKey(x.participant),x.session]);const current=latest.get(key);if(current===undefined||((x.updatedAt??0)>(current.updatedAt??0)))latest.set(key,x)}const winners=[...latest.values()];const u=new FileHostLedgerPort({userPath:this.user,localPath:this.local,writableScope:'user',readableScopes:['user'],now:this.clock});for(const x of winners){const result=await u.ensurePresence(x);if(result.status==='degraded')return{status:'degraded',bindings:winners,error:result.error}}return{status:'reconciled',bindings:winners}}catch(error){return{status:'degraded',bindings:b,error}}}}
export function createHostLedgerPort(o:HostLedgerFileAdapterOptions={}):HostLedgerPort{return new FileHostLedgerPort(o)}
