import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { withFileLock } from './file-lock.js';
import { nameKey } from './model.js';
import { isCurrentlyJoined } from './runtime.js';
import type { HostLedgerPort, HostLedgerScope, PresenceRecord, PresenceKey, PresenceLookup, PresenceResult, EvidenceRecord, EvidenceClaim, EvidenceLookup, EvidenceGc, ClaimResult, ReconcileBindingInput, ReconcileBindingResult } from './host-ledger.js';
const LOCK = { retryMs: 10, staleMs: 300000 } as const; const RETENTION = 7 * 86400000;
export interface HostLedgerFileAdapterOptions { userPath?: string; localPath?: string; writableScope?: HostLedgerScope; readableScopes?: readonly HostLedgerScope[]; now?: () => number }
async function canon(value:string):Promise<string>{const absolute=path.resolve(value);try{return await fs.realpath(absolute)}catch{return absolute}}
async function read<T extends {v:1;at?:number;updatedAt?:number}>(file:string,now:number):Promise<T[]>{try{return (await fs.readFile(file,'utf8')).split('\n').flatMap(line=>{try{const row=JSON.parse(line) as T;const at=row.at??row.updatedAt;return row.v===1&&typeof at==='number'&&at<=now&&at>=now-RETENTION?[row]:[]}catch{return[]}})}catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT')return[];throw e}}
async function write<T>(file:string,rows:readonly T[]):Promise<void>{await fs.mkdir(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.${Date.now()}.tmp`;await fs.writeFile(tmp,rows.length?rows.map(row=>JSON.stringify(row)).join('\n')+'\n':'',{mode:0o600});await fs.rename(tmp,file)}
function k(v:{location:string;participant:string;session:string;channel?:string;activity?:string;kind?:string}){return JSON.stringify([v.location,nameKey(v.participant),v.session,v.channel,v.activity,v.kind])}
export class FileHostLedgerPort implements HostLedgerPort { private readonly user:string;private readonly local:string;private readonly writable:HostLedgerScope;private readonly readable:readonly HostLedgerScope[];private readonly clock:()=>number; constructor(o:HostLedgerFileAdapterOptions={}){const testRoot=process.env.SQUARE_REGISTRY?path.dirname(process.env.SQUARE_REGISTRY):undefined;this.user=o.userPath??(testRoot??path.join(os.homedir(),'.square','host-ledger'));this.local=o.localPath??(testRoot??path.join(process.cwd(),'.square','host-ledger'));this.writable=o.writableScope??'local';this.readable=o.readableScopes??['user','local'];this.clock=o.now??Date.now} private file(s:HostLedgerScope,f:'presence'|'evidence'){return path.join(s==='user'?this.user:this.local,`${f}.ndjsonl`)}
async ensurePresence(i:PresenceRecord):Promise<PresenceResult>{const r={...i,location:await canon(i.location),...(this.writable==='local'?{route:undefined}:{}),updatedAt:i.updatedAt??this.clock(),v:1 as const};const f=this.file(this.writable,'presence');try{await withFileLock(f+'.lock',LOCK,async()=>write(f,[...(await read<typeof r>(f,this.clock())).filter(x=>k(x)!==k(r)),r]));return{status:'ensured',record:r}}catch(error){return{status:'degraded',record:r,error}}}
async removePresence(i:PresenceKey){const r={...i,location:await canon(i.location)},f=this.file(this.writable,'presence');await withFileLock(f+'.lock',LOCK,async()=>write(f,(await read<any>(f,this.clock())).filter(x=>k(x)!==k(r))))}
async listPresence(i:PresenceLookup={}):Promise<readonly PresenceRecord[]>{const loc=i.location===undefined?undefined:await canon(i.location),m=new Map<string,{record:any;scope:HostLedgerScope}>();for(const s of i.scopes??this.readable)for(const r of await read<any>(this.file(s,'presence'),i.now??this.clock())){if(loc&&r.location!==loc||i.participant&&nameKey(r.participant)!==nameKey(i.participant)||i.session&&r.session!==i.session)continue;const x=s==='user'?r:{...r,route:undefined},key=k(x),old=m.get(key);if(old?.scope==='user'&&s==='local')continue;if(!old||s==='user'||x.updatedAt>=old.record.updatedAt)m.set(key,{record:x,scope:s})}return[...m.values()].map(({record})=>record)}
async claimEvidence(i:EvidenceClaim):Promise<ClaimResult>{const f=this.file('user','evidence'),r={...i,location:await canon(i.location),outcome:'dispatching',at:i.now??this.clock(),v:1 as const};try{return await withFileLock(f+'.lock',LOCK,async()=>{const all=await read<any>(f,r.at),old=all.find(x=>k(x)===k(r));if(old)return old.outcome==='dispatching'?{status:'busy',record:old}:{status:'delivered',record:old};await write(f,[...all,r]);return{status:'acquired'}})}catch(error){return{status:'degraded',error}}}
async appendEvidence(i:EvidenceRecord){const f=this.file('user','evidence'),r={...i,location:await canon(i.location),at:i.at??this.clock(),v:1 as const};await withFileLock(f+'.lock',LOCK,async()=>{const all=await read<any>(f,r.at);await write(f,[...all.filter(x=>k(x)!==k(r)),r])})}
async listEvidence(i:EvidenceLookup={}):Promise<readonly EvidenceRecord[]>{const loc=i.location===undefined?undefined:await canon(i.location);return(await read<any>(this.file('user','evidence'),i.now??this.clock())).filter(r=>(!loc||r.location===loc)&&(!i.participant||nameKey(r.participant)===nameKey(i.participant))&&(!i.session||r.session===i.session)&&(!i.activity||r.activity===i.activity)&&(!i.kind||r.kind===i.kind))}
async gcEvidence(i:EvidenceGc){const f=this.file('user','evidence');await withFileLock(f+'.lock',LOCK,async()=>write(f,(await read<any>(f,this.clock())).filter(r=>r.at>=i.before)))}
async reconcileBinding(i:ReconcileBindingInput={}):Promise<ReconcileBindingResult>{let b:PresenceRecord[]=[];try{b=[...await this.listPresence({scopes:i.scopes,now:i.now})];if(i.artifact){const{state}=await i.artifact.read();const stale=b.filter(x=>!isCurrentlyJoined(state.acts as any,x.participant));for(const x of stale){for(const scope of i.scopes??this.readable){const remover=new FileHostLedgerPort({userPath:this.user,localPath:this.local,writableScope:scope,readableScopes:[scope],now:this.clock});await remover.removePresence(x)} }b=b.filter(x=>!stale.includes(x))}const u=new FileHostLedgerPort({userPath:this.user,localPath:this.local,writableScope:'user',readableScopes:['user'],now:this.clock});for(const x of b){const result=await u.ensurePresence({...x,route:undefined});if(result.status==='degraded')return{status:'degraded',bindings:b,error:result.error}}return{status:'reconciled',bindings:b}}catch(error){return{status:'degraded',bindings:b,error}}}}
export function createHostLedgerPort(o:HostLedgerFileAdapterOptions={}):HostLedgerPort{return new FileHostLedgerPort(o)}
