import os from 'node:os';
import path from 'node:path';
import { createHash } from 'node:crypto';

import { withFileLock } from './file-lock.js';
import { canonicalSquarePath, lookupSessionBindings } from './registry.js';
import { nameKey, sameName, type InboxMembership } from './model.js';
import { createHostLedgerPort } from './host-ledger-file-adapter.js';
import type { HostLedgerPort } from './host-ledger.js';
import { formatActivityId } from './square-core.js';

export interface PresentedAttention { sessionId: string; squarePath: string; name: string; actIndex: number; }
interface SelectedMembership { membership: InboxMembership; sessionId: string; }
const LOCK_STALE_MS = 5 * 60_000;
const LOCK_RETRY_MS = 10;

export function presentedPath(env: NodeJS.ProcessEnv = process.env): string { return env.SQUARE_PRESENTED || path.join(os.homedir(), '.square', 'presented.ndjsonl'); }
function evidence(env: NodeJS.ProcessEnv = process.env): ReturnType<typeof createHostLedgerPort> { const file = presentedPath(env); return createHostLedgerPort({ userPath: env.SQUARE_HOST_LEDGER_USER ?? path.dirname(file), writableScope: 'user', readableScopes: ['user'] }); }
export async function readPresentedAttentions(env: NodeJS.ProcessEnv = process.env, now = Date.now()): Promise<PresentedAttention[]> { return (await evidence(env).listEvidence({ kind: 'presentation', now })).map((row) => ({ sessionId: row.session, squarePath: row.location, name: row.participant, actIndex: Number(row.activity.slice(4)) })); }
async function membershipKey(membership: Pick<InboxMembership, 'squarePath' | 'name'>): Promise<string> { return `${await canonicalSquarePath(membership.squarePath)}\u0000${membership.name.toLocaleLowerCase()}`; }
async function attentionLockPath(filePath: string, membership: InboxMembership): Promise<string> { return `${filePath}.${createHash('sha256').update(await membershipKey(membership)).digest('hex')}.lock`; }
async function withAttentionLocks<T>(filePath: string, inbox: InboxMembership[], fn: () => T | Promise<T>, signal?: AbortSignal): Promise<T> { const lockPaths = [...new Set(await Promise.all(inbox.map((membership) => attentionLockPath(filePath, membership))))].sort(); async function acquire(index: number): Promise<T> { if (signal?.aborted) throw signal.reason ?? new Error('Presentation aborted'); if (index >= lockPaths.length) return fn(); return withFileLock(lockPaths[index], { retryMs: LOCK_RETRY_MS, staleMs: LOCK_STALE_MS, signal }, () => acquire(index + 1)); } return acquire(0); }
async function ownerFor(sessionId: string, membership: InboxMembership): Promise<string> { return sessionId; }
async function selectUnpresented(sessionId: string, inbox: InboxMembership[], rows: Awaited<ReturnType<HostLedgerPort['listEvidence']>>): Promise<SelectedMembership[]> { const known = new Set(rows.map((row) => `${row.session}\u0000${row.location}\u0000${nameKey(row.participant)}\u0000${row.activity}`)); const selected: SelectedMembership[] = []; for (const membership of inbox) { const session = await ownerFor(sessionId, membership); const location = await canonicalSquarePath(membership.squarePath); const notifications = membership.notifications.filter((notification) => !known.has(`${session}\u0000${location}\u0000${nameKey(membership.name)}\u0000${formatActivityId(notification.actIndex)}`)); if (notifications.length > 0) selected.push({ membership: { ...membership, notifications }, sessionId: session }); } return selected; }
export async function hasPresentedForOwner(sessionId: string, squarePath: string, name: string, actIndex: number, env: NodeJS.ProcessEnv = process.env, now = Date.now()): Promise<boolean> { const resolved = await canonicalSquarePath(squarePath); return (await evidence(env).listEvidence({ kind: 'presentation', now, location: resolved, participant: name, session: sessionId, activity: formatActivityId(actIndex) })).length > 0; }
export async function hasPresentedAttention(squarePath: string, name: string, actIndex: number, env: NodeJS.ProcessEnv = process.env, now = Date.now()): Promise<boolean> { return (await evidence(env).listEvidence({ kind: 'presentation', now, location: await canonicalSquarePath(squarePath), participant: name, activity: formatActivityId(actIndex) })).length > 0; }
export async function recordPresentedForOwner(sessionId: string, squarePath: string, name: string, actIndex: number, env: NodeJS.ProcessEnv = process.env, at = Date.now()): Promise<void> { await evidence(env).appendEvidence({ location: await canonicalSquarePath(squarePath), participant: name, session: sessionId, activity: formatActivityId(actIndex), kind: 'presentation', outcome: 'presented', at }); }
export async function presentOnce<T>(sessionId: string, lookup: (sessionId: string) => InboxMembership[] | Promise<InboxMembership[]>, deliver: (inbox: InboxMembership[]) => T | Promise<T>, env: NodeJS.ProcessEnv = process.env, at = Date.now(), signal?: AbortSignal): Promise<T | undefined> { const filePath = presentedPath(env); const initial = (await lookup(sessionId)).filter((membership) => membership.notifications.length > 0); if (initial.length === 0) return undefined; const lockedMemberships = new Set(await Promise.all(initial.map(membershipKey))); return withAttentionLocks(filePath, initial, async () => { const current: InboxMembership[] = []; for (const membership of await lookup(sessionId)) if (lockedMemberships.has(await membershipKey(membership))) current.push(membership); const selected = await selectUnpresented(sessionId, current, await evidence(env).listEvidence({ kind: 'presentation', now: at })); if (selected.length === 0) return undefined; if (signal?.aborted) throw signal.reason ?? new Error('Presentation aborted'); const result = await deliver(selected.map(({ membership }) => membership)); if (signal?.aborted) throw signal.reason ?? new Error('Presentation aborted'); for (const { membership, sessionId: selectedSession } of selected) for (const notification of membership.notifications) await evidence(env).appendEvidence({ location: await canonicalSquarePath(membership.squarePath), participant: membership.name, session: selectedSession, activity: formatActivityId(notification.actIndex), kind: 'presentation', outcome: 'presented', at }); return result; }, signal); }
